### ISSUE TITLE
Connection event is called twice

### ISSUE THREAD

**Issue by KyleRAnderson** [FRC2706/Dashboard.net#5]
When the robot is connected, for whatever reason the event that notifies the necessary function of the event is fired twice, causing problems.

**Comment by KyleRAnderson** [comment]
There's something very fishy happening here, not sure if it's a bug I created or a bug in NetworkTables. Whenever we connect, the OnConnection event is fired twice and the application hangs for a moment. Big problem.

**Comment by georgetzavelas** [comment]
Was there a working version you can go back to?

What is our backup plan? Is there an alternative we can use like the Smart Dashboard for all the required features needed by Drive team?  If so how much effort is required to get it working? 

Not to put pressure on you but we should have something that can be used by Drive team on Saturday so they can start practicing using the setup they will have at competition. If we feel we cannot provide something due to all of the NetworkTable issues we have encountered we should prepare them for the worst.

**Comment by KyleRAnderson** [comment]
@georgetzavelas it's not actually a major issue since the dashboard still has full functionality, it just hangs a little bit at the start. I do have working versions which don't hang, but they don't handle random disconnects.

**Comment by KyleRAnderson** [comment]
Determined that this is at least partially a Library problem: The library is calling the event twice. We can fix it in the code using a counter, but the hanging part is the Dashboard code's fault.

**Comment by georgetzavelas** [comment]
Awesome! Great work Kyle! So excited to see the end product.

**Comment by KyleRAnderson** [comment]
Found out that it's the camera stream causing the UI to hang. Eventually the logic behind the camera stream connection won't happen on robot connection but when the key for the camera  URL changes, and would happen in a different thread to prevent hanging.

**Comment by KyleRAnderson** [comment]
I've made an adequate solution for the event being called twice. As for the hanging, I've introduced multi-threading where appropriate to stop such hanging.

**Comment by KyleRAnderson** [comment]
Resolved in 234574a
